version: '3'

services:
  welcome:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${DOCKER_BRANCH}-welcome
    networks:
      - traefik-realt
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.welcome.rule=Host(`realt.community`) || Host(`www.realt.community`)"
      - "traefik.http.routers.welcome.entrypoints=websecure"
    restart: always

networks:
  traefik-realt:
    external: true
